export const LEADERBOARD_START = "LEADERBOARD_START";
export const LEADERBOARD_FAIL = "LEADERBOARD_FAIL";
export const LEADERBOARD_SUCCESS = "LEADERBOARD_SUCCESS";

export const USERDATA_SUCCESS = "USERDATA_SUCCESS";
export const USERDATA_LOGOUT = "USERDATA_LOGOUT";
