export const STAGE_CREATE = "STAGE_CREATE";

export const GENERATE_NEW_PIECE = "GENERATE_NEW_PIECE";
export const HOLD_PIECE = "HOLD_PIECE";
export const GET_HELD_PIECE = "GET_HELD_PIECE";
export const GET_NEXT_PIECE = "GET_NEXT_PIECE";
